version: "2"

services:
  # https://hub.docker.com/r/gitea/gitea
  server:
    image: gitea/gitea:1.20.5-rootless@sha256:5f188b3b300d4cf3e7fae4fe2272b2d8991234b85b06f21aa98a1efb0a886748
    volumes:
      - gitea-data:/var/lib/gitea
      - gitea-config:/etc/gitea
    ports:
      - "80:3000"
      - "22:22"
    # environment:
    #   - GITEA__server__LOCAL_ROOT_URL=http://localhost:80/

  # https://github.com/balenablocks/hostname
  hostname:
    build: hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: gitea

volumes:
  gitea-data:
  gitea-config:
