version: "2"

services:
  # https://hub.docker.com/r/gitea/gitea
  server:
    image: gitea/gitea:1.22.2-rootless@sha256:75b1e8f14a63eb33da4dc5d1032212a97fe322d76cf3c5b080611771e7a2f154
    volumes:
      - gitea-data:/var/lib/gitea
      - gitea-config:/etc/gitea
    ports:
      - "80:3000"
      - "22:22"
    # environment:
    #   - GITEA__server__LOCAL_ROOT_URL=http://localhost:80/

  # https://github.com/balenablocks/hostname
  hostname:
    build: hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: gitea

volumes:
  gitea-data:
  gitea-config:
