version: "2"

services:
  # https://hub.docker.com/r/gitea/gitea
  server:
    image: gitea/gitea:1.21.3-rootless@sha256:00677d8d32eddb4c9c61ef2834ee89d9b269036c6918081c3971a6009e7ed2c0
    volumes:
      - gitea-data:/var/lib/gitea
      - gitea-config:/etc/gitea
    ports:
      - "80:3000"
      - "22:22"
    # environment:
    #   - GITEA__server__LOCAL_ROOT_URL=http://localhost:80/

  # https://github.com/balenablocks/hostname
  hostname:
    build: hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: gitea

volumes:
  gitea-data:
  gitea-config:
