version: "2"

services:
  # https://hub.docker.com/r/gitea/gitea
  server:
    image: gitea/gitea:1.21.0-rootless@sha256:89e4d9f64c030a1415454259f58c517e81bbe9710db1e12a17849e2c198df301
    volumes:
      - gitea-data:/var/lib/gitea
      - gitea-config:/etc/gitea
    ports:
      - "80:3000"
      - "22:22"
    # environment:
    #   - GITEA__server__LOCAL_ROOT_URL=http://localhost:80/

  # https://github.com/balenablocks/hostname
  hostname:
    build: hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: gitea

volumes:
  gitea-data:
  gitea-config:
