version: "2"

services:
  # https://hub.docker.com/r/gitea/gitea
  server:
    image: gitea/gitea:1.18.3-rootless@sha256:c8104575eb83b31c403edeabdb4d189dc32d1913491faae5adb21aaa757c5300
    volumes:
      - gitea-data:/var/lib/gitea
      - gitea-config:/etc/gitea
    ports:
      - "80:3000"
      - "22:22"
    # environment:
    #   - GITEA__server__LOCAL_ROOT_URL=http://localhost:80/

  # https://github.com/balenablocks/hostname
  hostname:
    build: hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: gitea

volumes:
  gitea-data:
  gitea-config:
