name: balena

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fleet: [gh_klutchell/gitea-aarch64, gh_klutchell/gitea-amd64]

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: balena-io/deploy-to-balena-action@4fe12febf088f00f16c44f4c2bc613bd18da4863 # v2.0.16
        with:
          balena_token: ${{ secrets.BALENA_API_KEY }}
          fleet: ${{ matrix.fleet }}
          create_tag: true
