name: balena

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fleet: [gh_klutchell/gitea-aarch64, gh_klutchell/gitea-amd64]

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: balena-io/deploy-to-balena-action@e7041b7ca6dd85f47a3eb5ce141178bf77d85920 # v0.27.0
        with:
          balena_token: ${{ secrets.BALENA_API_KEY }}
          fleet: ${{ matrix.fleet }}
          create_tag: true
